### PR TITLE
Various improvements [breaks build under Haiku R1B4]

### PR DESCRIPTION
**Pull request by bitigchi**

### CODE REVIEW

**Comment by humdingerb** [comment]
Still builds and works, though some changes to use BNumberFormat appear to be done just for changes sake?
I dunno... If nobody more experiences has any input, I'd merge...

**Comment by korli** [comment]
> Still builds and works, though some changes to use BNumberFormat appear to be done just for changes sake? I dunno... If nobody more experiences has any input, I'd merge...

Build failed...

**Comment by bitigchi** [comment]
I know what you mean :). Ideally, all user facing numbers should be formatted to account for different locale settings. Other OS usually have this baked into their translation macros, but we have to do it manually for the time being…

**Comment by humdingerb** [comment]
> Build failed...

Hmm, works here with hrev57672, 64bit. Did a "jam clean && jam -qj8"...

**Comment by korli** [comment]
> Hmm, works here with hrev57672, 64bit. Did a "jam clean && jam -qj8"...

It failed on r1beta4

**Comment by bitigchi** [comment]
> > Hmm, works here with hrev57672, 64bit. Did a "jam clean && jam -qj8"...
> 
> 
> 
> It failed on r1beta4
> 
> 

That's normal, it uses API's not available on Beta 4.

**Comment by korli** [comment]
> That's normal, it uses API's not available on Beta 4.

What's the benefit of this PR then?

**Comment by bitigchi** [comment]
> 
> 
> > That's normal, it uses API's not available on Beta 4.
> 
> 
> 
> What's the benefit of this PR then?

What do you mean what's the benefit of this PR? Can you elaborate?

**Comment by korli** [comment]
> What do you mean what's the benefit of this PR? Can you elaborate?

Trying to understand what you want with this PR? It obviously can't be merged. Wait until the next release for a merge?

**Comment by bitigchi** [comment]
Well obviously? Is there a time-cap or something for submitting PR's?

You could just indicate something like "to be merged after next Haiku release", and be done with it. I have trouble understanding the reasons for these pointless questions.

**Comment by korli** [comment]
> You could just indicate something like "to be merged after next Haiku release", and be done with it. I have trouble understanding the reasons for these pointless questions.

Seems all clear now... Thanks.

**Comment by bitigchi** [comment]
> 
> 
> > You could just indicate something like "to be merged after next Haiku release", and be done with it. I have trouble understanding the reasons for these pointless questions.
> 
> 
> 
> Seems all clear now... Thanks.

Sorry if it sounded rude, I hope you understand what I mean.

**Comment by humdingerb** [comment]
Let's merge then and I'll add a reminder issue not to update the haikuports recipe (or require some nightly hrev) because it breaks the build under R1B4.

**Comment by korli** [comment]
So we can't fix anything for r1beta4 because of this, how nice. Please stop doing this.

**Comment by humdingerb** [comment]
Sorry, I apprently misinterpreted your "Seems all clear now"...

**Pull request merged**
